# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-07 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('abstract', models.TextField()),
                ('keywords', models.CharField(blank=True, max_length=200)),
                ('paper', models.FileField(blank=True, null=True, upload_to='papers/')),
                ('data', models.FileField(blank=True, null=True, upload_to='papers/data/')),
                ('code', models.FileField(blank=True, null=True, upload_to='papers/code/')),
                ('publish', models.CharField(choices=[('true', 'Yes'), ('false', 'No')], help_text='If "Yes", all files attached to this paper will be available for download.\n                     If paper has no attached file(s), just put "No"', max_length=5)),
                ('authors', models.ManyToManyField(to='people.Person')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
