# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-07 00:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import leeps_website.misc.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(help_text='All pages in this category can be accessed at /misc/category/&lt;slug&gt;')),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='<p class="help">Files can be linked in a Markdown document with [&lt;link-text&gt;](/site_media/&lt;filename&gt;).</p><p class="help">Or accessed directly at http://leeps.ucsc.edu/static/misc/&lt;filename&gt;.</p>', upload_to=leeps_website.misc.models.file_saver)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(help_text='Page can be accessed at /misc/page/&lt;slug&gt;')),
                ('content', models.TextField(help_text='Markdown syntax allowed (http://daringfireball.net/projects/markdown/syntax)')),
                ('javascript', models.TextField(blank=True)),
                ('css', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.Category')),
            ],
        ),
    ]
